// Code generated by cmd/contractgen; DO NOT EDIT.
package contractsync

const GeneratedRevision = "default"

var GeneratedEmployeeIDs = []string{"alex", "garth", "joanne", "ross", "tim"}

var GeneratedSkillIDs = []string{"create-company", "create-doc", "create-email", "delete-company", "read-company", "read-internet", "read-skills", "read-trends", "read-twitter", "read-user", "update-terms"}

type Tier1Alias struct { PatternID string; CanonicalID string }

var GeneratedTier1Aliases = []Tier1Alias{
	{PatternID: "create-company", CanonicalID: "create-company"},
	{PatternID: "create-doc", CanonicalID: "create-doc"},
	{PatternID: "create-email", CanonicalID: "create-email"},
	{PatternID: "delete-company", CanonicalID: "delete-company"},
	{PatternID: "read-company", CanonicalID: "read-company"},
	{PatternID: "read-google", CanonicalID: "read-internet"},
	{PatternID: "read-internet", CanonicalID: "read-internet"},
	{PatternID: "read-skills", CanonicalID: "read-skills"},
	{PatternID: "read-trends", CanonicalID: "read-trends"},
	{PatternID: "read-twitter", CanonicalID: "read-twitter"},
	{PatternID: "read-user", CanonicalID: "read-user"},
	{PatternID: "update-terms", CanonicalID: "update-terms"},
	{PatternID: "write-company", CanonicalID: "create-company"},
	{PatternID: "write-doc", CanonicalID: "create-doc"},
	{PatternID: "write-email", CanonicalID: "create-email"},
}

var GeneratedThreadPinSkillIDs = []string{"create-company", "create-doc", "create-email", "delete-company"}
