package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

type contract struct {
	Revision  string `json:"revision"`
	Employees []struct {
		ID string `json:"id"`
	} `json:"employees"`
	Skills []struct {
		ID string `json:"id"`
	} `json:"skills"`
	Tier1Aliases []struct {
		PatternID   string `json:"pattern_id"`
		CanonicalID string `json:"canonical_id"`
	} `json:"tier1_aliases"`
	ThreadPinSkillIDs []string `json:"thread_pin_skill_ids"`
}

func main() {
	var out string
	flag.StringVar(&out, "out", "", "output file")
	flag.Parse()
	if strings.TrimSpace(out) == "" {
		panic("missing -out")
	}

	contractPath, err := resolveContractPath()
	if err != nil {
		panic(err)
	}
	raw, err := os.ReadFile(contractPath)
	if err != nil {
		panic(err)
	}
	var c contract
	if err := json.Unmarshal(raw, &c); err != nil {
		panic(err)
	}
	employees := normalizeIDs(extractEmployeeIDs(c))
	skills := normalizeIDs(extractSkillIDs(c))
	threadPins := normalizeIDs(c.ThreadPinSkillIDs)
	aliases := normalizeAliases(c.Tier1Aliases)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/contractgen; DO NOT EDIT.\n")
	b.WriteString("package contractsync\n\n")
	b.WriteString("const GeneratedRevision = " + quote(strings.TrimSpace(c.Revision)) + "\n\n")
	b.WriteString("var GeneratedEmployeeIDs = []string{")
	for i, id := range employees {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(quote(id))
	}
	b.WriteString("}\n\n")
	b.WriteString("var GeneratedSkillIDs = []string{")
	for i, id := range skills {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(quote(id))
	}
	b.WriteString("}\n\n")
	b.WriteString("type Tier1Alias struct { PatternID string; CanonicalID string }\n\n")
	b.WriteString("var GeneratedTier1Aliases = []Tier1Alias{\n")
	for _, a := range aliases {
		b.WriteString("\t{PatternID: " + quote(a.PatternID) + ", CanonicalID: " + quote(a.CanonicalID) + "},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("var GeneratedThreadPinSkillIDs = []string{")
	for i, id := range threadPins {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(quote(id))
	}
	b.WriteString("}\n")

	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

func resolveContractPath() (string, error) {
	if p := strings.TrimSpace(os.Getenv("BIMROSS_CONTRACT_FILE")); p != "" {
		return p, nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	candidates := []string{
		filepath.Join(wd, "../../../cursor-rules/contracts/capability-contract-v1.json"),
		filepath.Join(wd, "../../../../cursor-rules/contracts/capability-contract-v1.json"),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c, nil
		}
	}
	return "", fmt.Errorf("unable to resolve capability-contract-v1.json; set BIMROSS_CONTRACT_FILE")
}

func extractEmployeeIDs(c contract) []string {
	out := make([]string, 0, len(c.Employees))
	for _, e := range c.Employees {
		out = append(out, e.ID)
	}
	return out
}

func extractSkillIDs(c contract) []string {
	out := make([]string, 0, len(c.Skills))
	for _, s := range c.Skills {
		out = append(out, s.ID)
	}
	return out
}

func normalizeIDs(in []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(in))
	for _, id := range in {
		id = strings.TrimSpace(id)
		if id == "" {
			continue
		}
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	slices.Sort(out)
	return out
}

func normalizeAliases(in []struct {
	PatternID   string `json:"pattern_id"`
	CanonicalID string `json:"canonical_id"`
}) []struct {
	PatternID   string `json:"pattern_id"`
	CanonicalID string `json:"canonical_id"`
} {
	out := make([]struct {
		PatternID   string `json:"pattern_id"`
		CanonicalID string `json:"canonical_id"`
	}, 0, len(in))
	seen := map[string]struct{}{}
	for _, a := range in {
		p := strings.TrimSpace(a.PatternID)
		c := strings.TrimSpace(a.CanonicalID)
		if p == "" || c == "" {
			continue
		}
		key := p + "=>" + c
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, struct {
			PatternID   string `json:"pattern_id"`
			CanonicalID string `json:"canonical_id"`
		}{PatternID: p, CanonicalID: c})
	}
	slices.SortFunc(out, func(a, b struct {
		PatternID   string `json:"pattern_id"`
		CanonicalID string `json:"canonical_id"`
	}) int {
		if a.PatternID != b.PatternID {
			return strings.Compare(a.PatternID, b.PatternID)
		}
		return strings.Compare(a.CanonicalID, b.CanonicalID)
	})
	return out
}

func quote(s string) string { return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"` }
